### ISSUE TITLE
Uploading large networks OOMs node.js

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero-server#51]
I had a few more instances where uploading 256x20 networks caused node to use up so much memory it got OOM-killed.

**Comment by MartinDevelopment** [comment]
Might sound really stupid, but what would happen if you were to increase swap.

**Comment by hydrogenpi** [comment]
install more ram?

**Comment by gcp** [comment]
>install more ram?

I could upgrade the VPS it's on if I were sure a) it is actually the problem b) it helps.

If it just gobbles up all memory regardless of how much is in the machine then it's no use.

**Comment by roy7** [comment]
I do have logging of ram stats at various steps. Maybe that will give us a clue. Can check in a while. We steam this now right? I don't get how it can use so much memory.

**Comment by gcp** [comment]
FWIW this was not an issue when I uploaded these last time. I suspected the inspection of network topology, but it seems that this was already optimized for RAM usage?

**Comment by roy7** [comment]
Qucik glance at the logs I did see a bunch of errors like this. I imagine when the server ran out of memory this started up.

XXX uploaded game #6485552: f8b88da611f34b786e6959d57bc6ff7f5d2ed084dc93bf4e7f5e15ebe2031250 ERROR: MongoError: write
 ECONNRESET
XXX  uploaded game #6485552: d832a669666eea5c4b304b2f3088251d50e32885857a4eede4ee021b0890a9b0 INCREMENT ERROR: MongoError: write ECONNRESET

**Comment by roy7** [comment]
On the node level:

MongoError: Topology was destroyed
    at nextFunction (/home/jroy/code/leela-zero-server/node_modules/mongodb-core/lib/cursor.js:545:27)
    at AggregationCursor.Cursor.next [as _next] (/home/jroy/code/leela-zero-server/node_modules/mongodb-core/lib/cursor.js:699:3)
    at nextObject (/home/jroy/code/leela-zero-server/node_modules/mongodb/lib/cursor.js:680:8)
    at /home/jroy/code/leela-zero-server/node_modules/mongodb/lib/cursor.js:282:5
    at new Promise (<anonymous>)
    at AggregationCursor.Cursor.next (/home/jroy/code/leela-zero-server/node_modules/mongodb/lib/cursor.js:274:10)
    at app.get.asyncMiddleware (/home/jroy/code/leela-zero-server/server.js:968:35)
    at /home/jroy/code/leela-zero-server/server.js:108:25
    at Layer.handle [as handle_request] (/home/jroy/code/leela-zero-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jroy/code/leela-zero-server/node_modules/express/lib/router/route.js:137:13)

**Comment by roy7** [comment]
@rchs819 Do you think it's possible to do https://github.com/gcp/leela-zero-server/pull/36 in a way that can work as a stream? Then if we rewrite submit-network we can write the file to disk, then read it back from disk while piping it through gunzip, your code, and ending with hash. I'm assuming something like ".pipe(filterblockcount)" could store the results in a global variable or something?

I've never written code to handle pipes, I've only use basic pipe calls to existing libraries so far.

**Comment by rchs819** [comment]
Sure, I'll try the piping method with ram usage logging before and after the piping.

@roy7 Regarding the error log you posted
Is this the first occurrence of the error?

**Comment by roy7** [comment]
Yeah. Just must be when the server ran out of ram, mongo also died or something else was going wrong. Never have problems like this unless my bad network upload code is filling all available memory and swap, lol. :)

**Comment by roy7** [comment]
Here's a memory logs so we have an idea what the old approach was doing.

submit-network begins
rss 129.84 MB
heapTotal 59.75 MB
heapUsed 23.43 MB
external 62.78 MB
unzip completed
rss 196.38 MB
heapTotal 58.59 MB
heapUsed 20.61 MB
external 124.12 MB
networkbuffer.toString() complete
rss 231.45 MB
heapTotal 93.73 MB
heapUsed 55.75 MB
external 124.12 MB
XXX  uploaded network 93f8b60c6c0f15fdf055073fd02fef428e5effcb5d50badb3861a7203c71ba91 (6435001)
Network weights (128 x 10) 93f8b60c6c0f15fdf055073fd02fef428e5effcb5d50badb3861a7203c71ba91 (6435001) uploaded!

**Comment by rchs819** [comment]
This is the memory log from local machine after #52 
```
submit-network begins
rss 232.01 MB
heapTotal 31.83 MB
heapUsed 19.65 MB
external 195.07 MB
unzip completed
rss 762.94 MB
heapTotal 50.83 MB
heapUsed 19.1 MB
external 715.86 MB
```

**Comment by rchs819** [comment]
Yes, unzip is now the bottleneck.

I'll search more alternative (more efficient) solutions for unzipping.

**Comment by roy7** [comment]
@rchs819 You're a hero!

**Comment by gcp** [comment]
>Just must be when the server ran out of ram, mongo also died or something else was going wrong. 

Yes, mongo died a few days ago just after I tried to upload 256x20. Or both node and mongo died, but node was restarted by the watcher.

**Comment by roy7** [comment]
Ok I merged the latest PR to reduce memory usage substantially. And @rchs819 might have an even better future version using busboy to not even store the network in ram at all. His tests reduce ram usage to about the minimum possible.

For now, the live server won't use over the size of the network when uploaded instead of 3x-4x that amount of memory like the old days.
